"""从手机端的 ArgForms.kt 生成平板端要用的 scripts/argforms.js。

为什么要生成而不是手抄：

服务端读参数有三种形态 —— 整包体放在 `args.input` 下、平铺、无参 —— 弄错哪一种
会在运行时以 ``missing `input` argument`` 失败。手机端那份 ArgForms.kt 本身就是
脚本生成的表（"Generated by gen_android_arg_forms.py -- do not edit"）。平板这边
如果手抄一份，两边一定会漂移，而漂移的表现是"某个命令静默没数据" —— 正是这个
项目已经踩过的那类坑。

所以：单一事实来源仍是手机端生成的那张表，这里只做格式转换（Kotlin → JS），
并把源文件的 sha256 写进产物头部，好让漂移可被发现。

用法：
    python tools/gen_argforms.py --src <手机端工程>/android/app/src/main/java/com/vrcx0/android/data/remote/ArgForms.kt
"""

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
APP = HERE.parent
DEMO = APP.parent  # tablet-mode/

# ArgForms.kt 属手机端工程（本仓库 android/ 模块），不在 tablet/ 内；
# 用 --src 指定它的路径。
DEFAULT_SOURCES = []

OUT = DEMO / "scripts" / "argforms.js"


def read_source(override):
    candidates = [Path(override)] if override else DEFAULT_SOURCES
    for p in candidates:
        if p.exists():
            return p
    raise SystemExit(
        "找不到 ArgForms.kt。它属于手机端工程（本仓库 android/ 模块的\n"
        "app/src/main/java/com/vrcx0/android/data/remote/ArgForms.kt）。用 --src 指定路径。"
    )


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//[^\n]*", "", text)
    return text


def parse_string_set(text, name):
    m = re.search(r"val\s+%s\s*:\s*Set<String>\s*=\s*setOf\((.*?)\)" % re.escape(name),
                  text, re.S)
    if not m:
        raise SystemExit(f"解析不出 {name}")
    return re.findall(r'"([^"]+)"', m.group(1))


def parse_string_list_map(text, name):
    m = re.search(r"val\s+%s\s*:\s*Map<String,\s*List<String>>\s*=\s*mapOf\((.*?)\n\s*\)"
                  % re.escape(name), text, re.S)
    if not m:
        raise SystemExit(f"解析不出 {name}")
    body = m.group(1)
    out = {}
    for entry in re.finditer(r'"([^"]+)"\s*to\s*listOf\(([^)]*)\)', body):
        key = entry.group(1)
        out[key] = re.findall(r'"([^"]+)"', entry.group(2))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=None, help="ArgForms.kt 路径")
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args()

    src = read_source(args.src)
    raw = src.read_text(encoding="utf-8")
    digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()[:16]
    text = strip_comments(raw)

    inputs = parse_string_set(text, "INPUT_COMMANDS")
    no_args = parse_string_set(text, "NO_ARG_COMMANDS")
    flat = parse_string_list_map(text, "FLAT_ARG_NAMES")

    if not inputs or not no_args:
        raise SystemExit("解析结果为空，拒绝生成空表（会造成静默的命令参数错形）")

    def js_array(items):
        return ",\n    ".join(json.dumps(i, ensure_ascii=False) for i in items)

    flat_lines = ",\n    ".join(
        f"{json.dumps(k, ensure_ascii=False)}: {json.dumps(v, ensure_ascii=False)}"
        for k, v in sorted(flat.items())
    )

    out = f"""/*
 * 由 android-app/tools/gen_argforms.py 生成 —— 不要手改。
 * 源: {src.name}  sha256:{digest}
 *   INPUT_COMMANDS {len(inputs)} 项 · FLAT_ARG_NAMES {len(flat)} 项 · NO_ARG_COMMANDS {len(no_args)} 项
 *
 * 服务端读参数有三种形态，弄错哪一种都会以 missing `input` argument 之类失败：
 *   INPUT_COMMANDS 的整包体放在 args.input 下；NO_ARG_COMMANDS 走 args:{{}}；其余平铺。
 * 用 ArgForms.encode(command, args) 拿到对的形态，不要自己拼。
 */
(function () {{
  'use strict';

  var INPUT_COMMANDS = [
    {js_array(inputs)}
  ];

  var FLAT_ARG_NAMES = {{
    {flat_lines}
  }};

  var NO_ARG_COMMANDS = [
    {js_array(no_args)}
  ];

  var inputSet = Object.create(null);
  for (var i = 0; i < INPUT_COMMANDS.length; i++) inputSet[INPUT_COMMANDS[i]] = true;
  var noArgSet = Object.create(null);
  for (var j = 0; j < NO_ARG_COMMANDS.length; j++) noArgSet[NO_ARG_COMMANDS[j]] = true;

  window.ArgForms = {{
    INPUT_COMMANDS: INPUT_COMMANDS,
    FLAT_ARG_NAMES: FLAT_ARG_NAMES,
    NO_ARG_COMMANDS: NO_ARG_COMMANDS,

    usesInput: function (command) {{ return !!inputSet[command]; }},
    needsNoArgs: function (command) {{ return !!noArgSet[command]; }},

    /** 按服务端要的形态包好 args。调用方永远传平铺的参数对象即可。 */
    encode: function (command, args) {{
      if (this.usesInput(command)) return {{ input: args || {{}} }};
      if (this.needsNoArgs(command)) return {{}};
      return args || {{}};
    }},

    /** 这个命令的参数名是否与表里登记的一致（拼错时给出提示，而不是静默失败）。 */
    unknownArgs: function (command, args) {{
      var allowed = this.FLAT_ARG_NAMES[command];
      if (!allowed || !args) return [];
      return Object.keys(args).filter(function (k) {{ return allowed.indexOf(k) < 0; }});
    }}
  }};
}})();
"""

    dest = Path(args.out)
    dest.write_text(out, encoding="utf-8")
    print(f"源        : {src}")
    print(f"sha256[:16]: {digest}")
    print(f"INPUT_COMMANDS {len(inputs)} · FLAT_ARG_NAMES {len(flat)} · NO_ARG_COMMANDS {len(no_args)}")
    print(f"写出      : {dest}  ({dest.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
