//! `app__local_*` commands, answered from the server's own database.
//!
//! GENERATED by `.workbuddy/scripts/generate_local_commands.py` from the
//! desktop command layer and `vrcx-0-composition`'s `local_data` facade.
//! Do not edit by hand: run `generate-remote-commands.sh` instead.
//!
//! Every arm calls the same facade method the desktop command calls, so a
//! query that works locally cannot behave differently when it is answered
//! remotely. The arms name no parameter types on purpose — `argument` infers
//! each one from the call it feeds.

use serde_json::Value as JsonValue;

use vrcx_0_composition::local_data::LocalDataRuntime;

use super::{argument, blocking, encode, CommandResult};

/// Every command in this table, for the client's capability check.
pub const COMMANDS: &[&str] = &[
    "app__activity_overlap_view",
    "app__activity_page_view",
    "app__activity_view",
    "app__avatar_feed_history_cleanup",
    "app__avatar_feed_persistence_set_disabled",
    "app__avatar_find_by_image_url",
    "app__avatar_get",
    "app__avatar_history_clear",
    "app__avatar_history_list",
    "app__avatar_tag_add",
    "app__avatar_tag_remove",
    "app__avatar_tag_update_color",
    "app__avatar_tags_distinct",
    "app__avatar_tags_get",
    "app__avatar_tags_list",
    "app__avatar_tags_patch",
    "app__avatar_tags_remove_all",
    "app__avatar_tags_replace",
    "app__avatar_time_spent_add",
    "app__avatar_time_spent_get",
    "app__avatar_time_spent_list",
    "app__avatar_usage_ranking",
    "app__browse_history_clear",
    "app__browse_history_delete",
    "app__browse_history_query",
    "app__browse_history_record",
    "app__browse_history_retention_days_get",
    "app__browse_history_retention_days_set",
    "app__config_list_values",
    "app__config_remove_value",
    "app__config_set_values",
    "app__database_maintenance_broken_game_log_display_names_get",
    "app__database_maintenance_broken_leave_entries_get",
    "app__database_maintenance_max_friend_log_number_get",
    "app__database_maintenance_table_sizes_get",
    "app__favorite_list",
    "app__favorite_local_snapshot",
    "app__feed_latest_query",
    "app__feed_persistence_set_disabled",
    "app__feed_rows_query",
    "app__feed_search_query",
    "app__friend_log_current_list",
    "app__friend_log_history_delete",
    "app__friend_log_history_query",
    "app__game_log_entry_delete",
    "app__game_log_instance_delete",
    "app__game_log_instance_delete_by_location",
    "app__game_log_previous_instances_by_group_id",
    "app__game_log_previous_instances_by_world_id",
    "app__game_log_query",
    "app__game_log_sessions_query",
    "app__instance_activity_dates_get",
    "app__instance_activity_rows_get",
    "app__instance_history_query",
    "app__local_moderation_get",
    "app__local_moderation_list",
    "app__memo_get_avatar",
    "app__memo_get_user",
    "app__memo_get_world",
    "app__memo_list_user_notes",
    "app__memo_list_users",
    "app__memo_save_avatar",
    "app__memo_save_user",
    "app__memo_save_world",
    "app__mutual_graph_fetch_cancel",
    "app__mutual_graph_fetch_start",
    "app__mutual_graph_friend_refresh",
    "app__mutual_graph_snapshot_get",
    "app__notification_add_v1",
    "app__notification_add_v2",
    "app__notification_delete",
    "app__notification_expire",
    "app__notification_list_query",
    "app__notification_update_expired",
    "app__notification_v2_expire",
    "app__notification_v2_mark_seen",
    "app__saved_group_collection_create",
    "app__saved_group_collection_delete",
    "app__saved_group_favorite_add",
    "app__saved_group_favorite_remove",
    "app__saved_group_favorites_get",
    "app__user_mutual_friends_list_get",
    "app__user_tables_ensure",
    "app__world_friend_visits",
    "app__world_get",
    "app__world_summaries_get",
    // Local favorite (VRCX's own DB, not the VRChat remote favorite) — the
    // generator skips these because `add`/`remove` route through a private
    // desktop helper and `group_*` live on `RuntimeHostState`, not `local_data`.
    "app__local_favorite_add",
    "app__local_favorite_remove",
];

/// Runs one `app__local_*` command, or `None` if the name belongs elsewhere.
pub async fn dispatch(
    local: &LocalDataRuntime,
    command: &str,
    args: &JsonValue,
) -> Option<CommandResult> {
    Some(match command {
        "app__activity_overlap_view" => {
            let input = match argument(args, "input") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.activity_overlap_view(input)))
        }
        "app__activity_page_view" => {
            let input = match argument(args, "input") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.activity_page_view(input)))
        }
        "app__activity_view" => {
            let input = match argument(args, "input") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.activity_view(input)))
        }
        "app__avatar_feed_history_cleanup" => {
            let cutoff_date = match argument(args, "cutoffDate") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.cleanup_avatar_feed_history(cutoff_date)))
        }
        "app__avatar_feed_persistence_set_disabled" => {
            let disabled = match argument(args, "disabled") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.set_avatar_feed_persistence_disabled(disabled)))
        }
        "app__avatar_find_by_image_url" => {
            let image_url = match argument(args, "imageUrl") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.avatar_find_by_image_url(image_url)))
        }
        "app__avatar_get" => {
            let input = match argument(args, "input") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(local.avatar_get(input).await)
        }
        "app__avatar_history_clear" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.avatar_history_clear(user_id)))
        }
        "app__avatar_history_list" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let limit = match argument(args, "limit") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.avatar_history_list(user_id, limit)))
        }
        "app__avatar_tag_add" => {
            let avatar_id = match argument(args, "avatarId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let tag = match argument(args, "tag") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let color = match argument(args, "color") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.avatar_tag_add(avatar_id, tag, color)))
        }
        "app__avatar_tag_remove" => {
            let avatar_id = match argument(args, "avatarId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let tag = match argument(args, "tag") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.avatar_tag_remove(avatar_id, tag)))
        }
        "app__avatar_tag_update_color" => {
            let avatar_id = match argument(args, "avatarId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let tag = match argument(args, "tag") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let color = match argument(args, "color") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.avatar_tag_update_color(avatar_id, tag, color)))
        }
        "app__avatar_tags_distinct" => {
            encode(blocking(|| local.avatar_tags_distinct()))
        }
        "app__avatar_tags_get" => {
            let avatar_id = match argument(args, "avatarId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.avatar_tags_get(avatar_id)))
        }
        "app__avatar_tags_list" => {
            encode(blocking(|| local.avatar_tags_list()))
        }
        "app__avatar_tags_patch" => {
            let avatar_id = match argument(args, "avatarId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let patch = match argument(args, "patch") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.avatar_tags_patch(avatar_id, patch)))
        }
        "app__avatar_tags_remove_all" => {
            let avatar_id = match argument(args, "avatarId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.avatar_tags_remove_all(avatar_id)))
        }
        "app__avatar_tags_replace" => {
            let avatar_id = match argument(args, "avatarId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let entries = match argument(args, "entries") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.avatar_tags_replace(avatar_id, entries)))
        }
        "app__avatar_time_spent_add" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let avatar_id = match argument(args, "avatarId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let time_spent = match argument(args, "timeSpent") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.avatar_time_spent_add(user_id, avatar_id, time_spent)))
        }
        "app__avatar_time_spent_get" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let avatar_id = match argument(args, "avatarId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.avatar_time_spent_get(user_id, avatar_id)))
        }
        "app__avatar_time_spent_list" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.avatar_time_spent_list(user_id)))
        }
        "app__avatar_usage_ranking" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let limit = match argument(args, "limit") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.avatar_usage_ranking(user_id, limit)))
        }
        "app__browse_history_clear" => {
            let owner_user_id = match argument(args, "ownerUserId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let entity_kind = match argument(args, "entityKind") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.browse_history_clear(owner_user_id, entity_kind)))
        }
        "app__browse_history_delete" => {
            let owner_user_id = match argument(args, "ownerUserId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let entity_kind = match argument(args, "entityKind") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let entity_id = match argument(args, "entityId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.browse_history_delete(owner_user_id, entity_kind, entity_id)))
        }
        "app__browse_history_query" => {
            let input = match argument(args, "input") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.browse_history_query(input)))
        }
        "app__browse_history_record" => {
            let input = match argument(args, "input") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.browse_history_record(input)))
        }
        "app__browse_history_retention_days_get" => {
            encode(blocking(|| local.browse_history_retention_days_get()))
        }
        "app__browse_history_retention_days_set" => {
            let retention_days = match argument(args, "retentionDays") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.browse_history_retention_days_set(retention_days)))
        }
        "app__config_list_values" => {
            encode(blocking(|| local.config_list_values()))
        }
        "app__config_remove_value" => {
            let key = match argument(args, "key") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.config_remove_value(key)))
        }
        "app__config_set_values" => {
            let entries = match argument(args, "entries") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.config_set_values(entries)))
        }
        "app__database_maintenance_broken_game_log_display_names_get" => {
            encode(blocking(|| local.broken_game_log_display_names()))
        }
        "app__database_maintenance_broken_leave_entries_get" => {
            encode(blocking(|| local.broken_leave_entries()))
        }
        "app__database_maintenance_max_friend_log_number_get" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.max_friend_log_number(user_id)))
        }
        "app__database_maintenance_table_sizes_get" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.maintenance_table_sizes(user_id)))
        }
        "app__favorite_list" => {
            let kind = match argument(args, "kind") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.favorite_list(kind)))
        }
        "app__favorite_local_snapshot" => {
            let kind = match argument(args, "kind") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.favorite_snapshot(kind)))
        }
        "app__feed_latest_query" => {
            let query = match argument(args, "query") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.query_feed_latest(query)))
        }
        "app__feed_persistence_set_disabled" => {
            let disabled = match argument(args, "disabled") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.set_feed_persistence_disabled(disabled)))
        }
        "app__feed_rows_query" => {
            let query = match argument(args, "query") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.feed_rows_query(query)))
        }
        "app__feed_search_query" => {
            let query = match argument(args, "query") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.query_feed_search(query)))
        }
        "app__friend_log_current_list" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.friend_log_current_list(user_id)))
        }
        "app__friend_log_history_delete" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let entry = match argument(args, "entry") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.friend_log_history_delete(user_id, entry)))
        }
        "app__friend_log_history_query" => {
            let query = match argument(args, "query") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.friend_log_history_query(query)))
        }
        "app__game_log_entry_delete" => {
            let kind = match argument(args, "kind") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let entry = match argument(args, "entry") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.game_log_entry_delete(kind, entry)))
        }
        "app__game_log_instance_delete" => {
            let location = match argument(args, "location") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let event_ids = match argument(args, "eventIds") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.game_log_instance_delete(location, event_ids)))
        }
        "app__game_log_instance_delete_by_location" => {
            let location = match argument(args, "location") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.game_log_instance_delete_by_location(location)))
        }
        "app__game_log_previous_instances_by_group_id" => {
            let group_id = match argument(args, "groupId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.previous_instances_by_group_id(group_id)))
        }
        "app__game_log_previous_instances_by_world_id" => {
            let world_id = match argument(args, "worldId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.previous_instances_by_world_id(world_id)))
        }
        "app__game_log_query" => {
            let query = match argument(args, "query") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.game_log_query(query)))
        }
        "app__game_log_sessions_query" => {
            let input = match argument(args, "input") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.game_log_sessions_query(input)))
        }
        "app__instance_activity_dates_get" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.instance_activity_dates_get(user_id)))
        }
        "app__instance_activity_rows_get" => {
            let start_date = match argument(args, "startDate") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let end_date = match argument(args, "endDate") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.instance_activity_rows_get(start_date, end_date)))
        }
        "app__instance_history_query" => {
            let input = match argument(args, "input") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.instance_history_query(input)))
        }
        "app__local_moderation_get" => {
            let owner_user_id = match argument(args, "ownerUserId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.local_moderation_get(owner_user_id, user_id)))
        }
        "app__local_moderation_list" => {
            let owner_user_id = match argument(args, "ownerUserId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.local_moderation_list(owner_user_id)))
        }
        "app__memo_get_avatar" => {
            let avatar_id = match argument(args, "avatarId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.memo_get_avatar(avatar_id)))
        }
        "app__memo_get_user" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.memo_get_user(user_id)))
        }
        "app__memo_get_world" => {
            let world_id = match argument(args, "worldId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.memo_get_world(world_id)))
        }
        "app__memo_list_user_notes" => {
            let owner_user_id = match argument(args, "ownerUserId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.memo_list_user_notes(owner_user_id)))
        }
        "app__memo_list_users" => {
            encode(blocking(|| local.memo_list_users()))
        }
        "app__memo_save_avatar" => {
            let avatar_id = match argument(args, "avatarId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let memo = match argument(args, "memo") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.memo_save_avatar(avatar_id, memo)))
        }
        "app__memo_save_user" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let memo = match argument(args, "memo") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.memo_save_user(user_id, memo)))
        }
        "app__memo_save_world" => {
            let world_id = match argument(args, "worldId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let memo = match argument(args, "memo") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.memo_save_world(world_id, memo)))
        }
        "app__mutual_graph_fetch_cancel" => {
            let input = match argument(args, "input") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.mutual_graph_fetch_cancel(input)))
        }
        "app__mutual_graph_fetch_start" => {
            let input = match argument(args, "input") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.mutual_graph_fetch_start(input)))
        }
        "app__mutual_graph_friend_refresh" => {
            let input = match argument(args, "input") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(local.mutual_graph_friend_refresh(input).await)
        }
        "app__mutual_graph_snapshot_get" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.mutual_graph_snapshot_get(user_id)))
        }
        "app__notification_add_v1" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let notification = match argument(args, "notification") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.notification_add_v1(user_id, notification)))
        }
        "app__notification_add_v2" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let notification = match argument(args, "notification") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.notification_add_v2(user_id, notification)))
        }
        "app__notification_delete" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let id = match argument(args, "id") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.notification_delete(user_id, id)))
        }
        "app__notification_expire" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let id = match argument(args, "id") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.notification_expire(user_id, id)))
        }
        "app__notification_list_query" => {
            let query = match argument(args, "query") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.notification_list_query(query)))
        }
        "app__notification_update_expired" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let id = match argument(args, "id") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let expired = match argument(args, "expired") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.notification_update_expired(user_id, id, expired)))
        }
        "app__notification_v2_expire" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let id = match argument(args, "id") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.notification_v2_expire(user_id, id)))
        }
        "app__notification_v2_mark_seen" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let id = match argument(args, "id") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.notification_v2_mark_seen(user_id, id)))
        }
        "app__saved_group_collection_create" => {
            let input = match argument(args, "input") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.saved_group_collection_create(input)))
        }
        "app__saved_group_collection_delete" => {
            let input = match argument(args, "input") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.saved_group_collection_delete(input)))
        }
        "app__saved_group_favorite_add" => {
            let input = match argument(args, "input") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.saved_group_favorite_add(input)))
        }
        "app__saved_group_favorite_remove" => {
            let input = match argument(args, "input") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.saved_group_favorite_remove(input)))
        }
        "app__saved_group_favorites_get" => {
            encode(blocking(|| local.saved_group_favorites_snapshot()))
        }
        "app__user_mutual_friends_list_get" => {
            let input = match argument(args, "input") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(local.user_mutual_friends_list(input).await)
        }
        "app__user_tables_ensure" => {
            let user_id = match argument(args, "userId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.ensure_user_tables(user_id)))
        }
        "app__world_friend_visits" => {
            let world_id = match argument(args, "worldId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.world_friend_visits(world_id)))
        }
        "app__world_get" => {
            let input = match argument(args, "input") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(local.world_get(input).await)
        }
        "app__world_summaries_get" => {
            let world_ids = match argument(args, "worldIds") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.world_summaries_get(world_ids)))
        }
        // Local favorite (VRCX's own SQLite DB, already on the server) — these
        // were listed in `COMMANDS` but had no arm, so they fell through to
        // `None` and the client ran them against its own (now-empty) runtime.
        // `add`/`remove` route through `LocalDataRuntime`, exactly like every
        // other arm here, so the server answers them directly.
        "app__local_favorite_add" => {
            let kind = match argument(args, "kind") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let entity_id = match argument(args, "entityId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let group_name = match argument(args, "groupName") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.favorite_add_local(kind, entity_id, group_name)))
        }
        "app__local_favorite_remove" => {
            let kind = match argument(args, "kind") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let entity_id = match argument(args, "entityId") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            let group_name = match argument(args, "groupName") {
                Ok(value) => value,
                Err(error) => return Some(CommandResult::Failed(error)),
            };
            encode(blocking(|| local.favorite_remove_local(kind, entity_id, group_name)))
        }
        _ => return None,
    })
}
