#!/usr/bin/env python3
"""Generate the Android client's command argument-shape table.

Why generated: the server takes arguments in TWO shapes and picking the wrong
one fails at runtime with ``missing `input` argument``. The shapes are decided
by server code (`parse_required(args)` vs `argument(args, "key")`), so the only
honest source is the same extraction that produces the API doc.

Input   docs/ANDROID_API-commands.json   (from gen_android_api_doc.py)
Output  android/app/src/main/java/com/vrcx0/android/data/remote/ArgForms.kt
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "docs" / "ANDROID_API-commands.json"
OUT = (
    ROOT / "android" / "app" / "src" / "main" / "java"
    / "com" / "vrcx0" / "android" / "data" / "remote" / "ArgForms.kt"
)


def kt_string_list(values: list[str], indent: str) -> str:
    if not values:
        return "emptyList()"
    return "\n" + "\n".join(f'{indent}"{v}",' for v in values) + f"\n{indent}"


def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    use_input = sorted(n for n, e in data.items() if e["input"])
    flat = {
        n: sorted(e["args"])
        for n, e in sorted(data.items())
        if not e["input"] and e["args"]
    }
    no_args = sorted(
        n for n, e in data.items() if not e["input"] and not e["args"]
    )

    L: list[str] = []
    w = L.append
    w("package com.vrcx0.android.data.remote")
    w("")
    w("/**")
    w(" * Generated by `.workbuddy/scripts/gen_android_arg_forms.py` -- do not edit.")
    w(" *")
    w(" * The server reads arguments in two different shapes and mixing them up")
    w(" * fails at runtime with ``missing `input` argument``. Re-run the generator")
    w(" * after every server-side command migration.")
    w(" *")
    w(" *   INPUT_COMMANDS  -> `args: { \"input\": <object> }`")
    w(" *   FLAT_ARG_NAMES  -> `args: { \"key\": value, ... }` (camelCase)")
    w(" *   NO_ARG_COMMANDS -> `args: {}`")
    w(" */")
    w("object ArgForms {")
    w("")
    w("    /** Commands whose whole body goes under `args.input`. */")
    w("    val INPUT_COMMANDS: Set<String> = setOf(")
    for n in use_input:
        w(f'        "{n}",')
    w("    )")
    w("")
    w("    /** Commands taking named parameters, mapped to their parameter names. */")
    w("    val FLAT_ARG_NAMES: Map<String, List<String>> = mapOf(")
    for n, args in flat.items():
        joined = ", ".join(f'"{a}"' for a in args)
        w(f'        "{n}" to listOf({joined}),')
    w("    )")
    w("")
    w("    /** Commands that take no arguments at all. */")
    w("    val NO_ARG_COMMANDS: Set<String> = setOf(")
    for n in no_args:
        w(f'        "{n}",')
    w("    )")
    w("")
    w("    fun usesInput(command: String): Boolean = command in INPUT_COMMANDS")
    w("}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"input={len(use_input)} flat={len(flat)} noArg={len(no_args)}")
    print(f"written: {OUT}")


if __name__ == "__main__":
    main()
