//! Invite codes, and the two things a code can do.
//!
//! The server used to have exactly one invitation: a single server-wide string
//! that either matched or did not. That is enough to gate "may this caller
//! create an account at all", but it cannot express what an operator actually
//! wants to hand out. Two distinct meanings are wanted:
//!
//! * **new account** — the claimant gets a tenant of their own: its own data
//!   directory, database, VRChat session and token. One code per person.
//! * **join an existing account** — the claimant gets a credential into an
//!   account that already exists (the operator's own, or a friend's), with no
//!   new session and no separate copy of the data. Several codes may name the
//!   same account: "same account, different codes".
//!
//! Codes are generated by an operator command (`--generate-invite`), stored in
//! `invites.json` next to the tenant registry, and read fresh on every claim,
//! so a running server picks a new code up without a restart. The legacy
//! server-wide `--invite` keeps working and behaves as an unlimited
//! new-account code, so deployments that set one do not have to change.
//!
//! Unlike bearer tokens, codes are stored in plaintext. That is deliberate: a
//! code is meant to be handed around and *re-read by the operator* (the whole
//! point of `--list-invites`), and its blast radius is bounded by use counts
//! and revocation rather than by storage secrecy. Tenant tokens stay
//! digest-only; this file holds nothing that grants durable silent access by
//! itself — every use produces a token the operator can see the count of.

use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

use vrcx_0_local_server::{generate_token, tokens_match};

use crate::tenants::TenantError;

/// File name, relative to the server's data root.
pub const INVITES_FILE: &str = "invites.json";
/// Bumped if the on-disk shape changes incompatibly.
const INVITES_VERSION: u32 = 1;
/// Length of a generated code. 24 characters of the same CSPRNG output the
/// bearer tokens come from — long enough that guessing is pointless, short
/// enough to type once by hand if it comes to that.
const CODE_LEN: usize = 24;

fn unix_now() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum InviteKind {
    /// Opens a brand-new account when claimed.
    New,
    /// Admits the claimant into `tenant_id`, the account the code names.
    Join,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InviteRecord {
    pub code: String,
    pub kind: InviteKind,
    /// The account a `join` code admits into. `None` for `New`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
    /// Free-form operator note ("for the living-room PC").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    /// Unix seconds.
    pub created_at: u64,
    /// Claim limit. `None` means unlimited.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_uses: Option<u32>,
    #[serde(default)]
    pub used: u32,
    /// Set when the operator revoked the code; kept in the file so `--list`
    /// still shows what was handed out.
    #[serde(default)]
    pub disabled: bool,
}

impl InviteRecord {
    pub fn remaining(&self) -> Option<u32> {
        self.max_uses.map(|max| max.saturating_sub(self.used))
    }

    pub fn usable(&self) -> bool {
        !self.disabled && self.remaining().map_or(true, |left| left > 0)
    }
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct InvitesFile {
    version: u32,
    #[serde(default)]
    invites: Vec<InviteRecord>,
}

pub fn read_invites(data_root: &Path) -> Result<Vec<InviteRecord>, TenantError> {
    let path = data_root.join(INVITES_FILE);
    if !path.exists() {
        return Ok(Vec::new());
    }
    let raw = std::fs::read_to_string(&path).map_err(|e| TenantError::Io(e.to_string()))?;
    let file: InvitesFile =
        serde_json::from_str(&raw).map_err(|e| TenantError::Parse(e.to_string()))?;
    Ok(file.invites)
}

pub fn write_invites(data_root: &Path, invites: &[InviteRecord]) -> Result<(), TenantError> {
    let file = InvitesFile {
        version: INVITES_VERSION,
        invites: invites.to_vec(),
    };
    let json = serde_json::to_string_pretty(&file)
        .map_err(|e| TenantError::Parse(e.to_string()))?;
    let path = data_root.join(INVITES_FILE);
    // Write-then-rename: the server reads this file on every claim, and a
    // half-written file must never be possible to observe.
    let temporary = path.with_extension("json.tmp");
    std::fs::write(&temporary, json).map_err(|e| TenantError::Io(e.to_string()))?;
    std::fs::rename(&temporary, &path).map_err(|e| TenantError::Io(e.to_string()))?;
    Ok(())
}

/// Creates a fresh code that collides with nothing already on this server.
///
/// `legacy` is the server-wide code from `--invite`, if one is configured —
/// generated codes must not shadow it, or a claim meant for a new code would
/// be ambiguous in the operator's mind.
pub fn generate_code(data_root: &Path, legacy: Option<&str>) -> Result<String, TenantError> {
    let existing = read_invites(data_root)?;
    for _ in 0..64 {
        let raw = generate_token().map_err(|e| TenantError::Runtime(e.to_string()))?;
        let code: String = raw.chars().take(CODE_LEN).collect();
        let taken = existing
            .iter()
            .any(|invite| tokens_match(&code, &invite.code))
            || legacy.is_some_and(|value| tokens_match(&code, value));
        if !taken {
            return Ok(code);
        }
    }
    Err(TenantError::Runtime(
        "could not generate a unique invite code".into(),
    ))
}

/// Appends a new invite (generating its code) and persists the file.
pub fn create_invite(
    data_root: &Path,
    kind: InviteKind,
    tenant_id: Option<String>,
    note: Option<String>,
    max_uses: Option<u32>,
    legacy: Option<&str>,
) -> Result<InviteRecord, TenantError> {
    let mut invites = read_invites(data_root)?;
    let record = InviteRecord {
        code: generate_code(data_root, legacy)?,
        kind,
        tenant_id: match kind {
            InviteKind::New => None,
            InviteKind::Join => tenant_id,
        },
        note: note.filter(|value| !value.trim().is_empty()),
        created_at: unix_now(),
        max_uses,
        used: 0,
        disabled: false,
    };
    invites.push(record.clone());
    write_invites(data_root, &invites)?;
    Ok(record)
}

/// Removes a code from the store and returns it.
///
/// Removal rather than a `disabled` flag: a revoked code has no reason to keep
/// occupying the list, and the operator who wants an audit trail has the log
/// line this prints. (The `disabled` field remains for records that were
/// disabled elsewhere and for forward compatibility.)
pub fn revoke_invite(data_root: &Path, code: &str) -> Result<InviteRecord, TenantError> {
    let mut invites = read_invites(data_root)?;
    let index = invites
        .iter()
        .position(|invite| tokens_match(&invite.code, code))
        .ok_or_else(|| TenantError::NotFound(format!("invite {code}")))?;
    let removed = invites.remove(index);
    write_invites(data_root, &invites)?;
    Ok(removed)
}

/// What a claim attempt decided, once its code (if any) has been interpreted.
pub enum Admission {
    /// Proceed as a new account. `invite_code` names the store entry to count
    /// a use against; `None` means the legacy server-wide code.
    New { invite_code: Option<String> },
    /// Join the account `tenant_id` names. `invite_code` names the store
    /// entry to count a use against.
    Join {
        tenant_id: String,
        invite_code: String,
    },
}

/// Decides whether a non-first claim may proceed, and what it means.
///
/// Order matters: per-code invites are checked before the legacy server-wide
/// one, so an operator can move to per-code invitations without changing the
/// old setting, and a code that was revoked takes effect even if the legacy
/// code would have matched something else.
pub fn resolve_admission(
    invites: &[InviteRecord],
    legacy_invite: Option<&str>,
    supplied: Option<&str>,
) -> Result<Admission, TenantError> {
    let Some(supplied) = supplied else {
        return Err(TenantError::AdmissionDenied);
    };

    if let Some(invite) = invites
        .iter()
        .find(|invite| invite.usable() && tokens_match(supplied, &invite.code))
    {
        return match invite.kind {
            InviteKind::New => Ok(Admission::New {
                invite_code: Some(invite.code.clone()),
            }),
            InviteKind::Join => {
                let Some(tenant_id) = invite.tenant_id.clone() else {
                    // A join code with no target cannot admit anyone; treating
                    // it as "denied" beats admitting into an arbitrary account.
                    return Err(TenantError::AdmissionDenied);
                };
                Ok(Admission::Join {
                    tenant_id,
                    invite_code: invite.code.clone(),
                })
            }
        };
    }

    if let Some(expected) = legacy_invite {
        if tokens_match(supplied, expected) {
            // The legacy code has no store entry to count against; it is the
            // server's configured value and stays unlimited, as before.
            return Ok(Admission::New { invite_code: None });
        }
    }

    Err(TenantError::AdmissionDenied)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn invite(code: &str, kind: InviteKind, tenant: Option<&str>) -> InviteRecord {
        InviteRecord {
            code: code.to_string(),
            kind,
            tenant_id: tenant.map(str::to_string),
            note: None,
            created_at: 0,
            max_uses: Some(1),
            used: 0,
            disabled: false,
        }
    }

    #[test]
    fn a_new_code_admits_a_new_account() {
        let invites = vec![invite("code-a", InviteKind::New, None)];
        match resolve_admission(&invites, None, Some("code-a")) {
            Ok(Admission::New {
                invite_code: Some(code),
            }) => assert_eq!(code, "code-a"),
            _ => panic!("expected a new-account admission"),
        }
    }

    #[test]
    fn a_join_code_names_its_account() {
        let invites = vec![invite("code-b", InviteKind::Join, Some("tenant-1"))];
        match resolve_admission(&invites, None, Some("code-b")) {
            Ok(Admission::Join {
                tenant_id,
                invite_code,
            }) => {
                assert_eq!(tenant_id, "tenant-1");
                assert_eq!(invite_code, "code-b");
            }
            _ => panic!("expected a join admission"),
        }
    }

    #[test]
    fn several_codes_can_name_the_same_account() {
        let invites = vec![
            invite("code-1", InviteKind::Join, Some("tenant-1")),
            invite("code-2", InviteKind::Join, Some("tenant-1")),
        ];
        for code in ["code-1", "code-2"] {
            match resolve_admission(&invites, None, Some(code)) {
                Ok(Admission::Join { tenant_id, .. }) => assert_eq!(tenant_id, "tenant-1"),
                _ => panic!("expected a join admission for {code}"),
            }
        }
    }

    #[test]
    fn exhausted_and_revoked_codes_are_refused() {
        let mut used_up = invite("code-c", InviteKind::New, None);
        used_up.used = 1;
        let mut revoked = invite("code-d", InviteKind::New, None);
        revoked.disabled = true;
        let invites = vec![used_up, revoked];
        assert!(resolve_admission(&invites, None, Some("code-c")).is_err());
        assert!(resolve_admission(&invites, None, Some("code-d")).is_err());
        assert!(resolve_admission(&invites, None, Some("nope")).is_err());
    }

    #[test]
    fn unlimited_codes_keep_admitting() {
        let mut record = invite("code-e", InviteKind::New, None);
        record.max_uses = None;
        record.used = 10_000;
        let invites = vec![record];
        assert!(resolve_admission(&invites, None, Some("code-e")).is_ok());
    }

    #[test]
    fn the_legacy_code_behaves_as_an_unlimited_new_account_code() {
        match resolve_admission(&[], Some("legacy"), Some("legacy")) {
            Ok(Admission::New { invite_code: None }) => {}
            _ => panic!("expected the legacy code to admit a new account"),
        }
        // And a per-code entry still wins when both could match.
        let invites = vec![invite("legacy", InviteKind::Join, Some("tenant-9"))];
        match resolve_admission(&invites, Some("legacy"), Some("legacy")) {
            Ok(Admission::Join { tenant_id, .. }) => assert_eq!(tenant_id, "tenant-9"),
            _ => panic!("expected the stored code to take precedence"),
        }
    }

    #[test]
    fn a_join_code_without_a_target_is_refused() {
        let invites = vec![invite("code-f", InviteKind::Join, None)];
        assert!(resolve_admission(&invites, None, Some("code-f")).is_err());
    }

    #[test]
    fn store_round_trips_and_codes_are_unique() {
        let dir = std::env::temp_dir().join(format!("vrcx-invites-test-{}", unix_now()));
        std::fs::create_dir_all(&dir).unwrap();
        let first = create_invite(&dir, InviteKind::New, None, Some("a".into()), Some(1), None)
            .expect("create");
        let second = create_invite(
            &dir,
            InviteKind::Join,
            Some("tenant-x".into()),
            None,
            None,
            None,
        )
        .expect("create");
        assert_ne!(first.code, second.code);
        assert_eq!(first.code.len(), CODE_LEN);

        let loaded = read_invites(&dir).expect("read");
        assert_eq!(loaded.len(), 2);
        assert_eq!(loaded[1].kind, InviteKind::Join);
        assert_eq!(loaded[1].tenant_id.as_deref(), Some("tenant-x"));
        assert_eq!(loaded[0].max_uses, Some(1));

        let removed = revoke_invite(&dir, &first.code).expect("revoke");
        assert_eq!(removed.code, first.code);
        assert_eq!(read_invites(&dir).expect("read").len(), 1);

        std::fs::remove_dir_all(&dir).ok();
    }
}
